// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIykaUQkxwiS_W4Ka_mnDecvsXrhkWYg',
    appId: '1:736300186589:web:bcb01fb43adcc7e235d434',
    messagingSenderId: '736300186589',
    projectId: 'pawtner-f96ee',
    authDomain: 'pawtner-f96ee.firebaseapp.com',
    storageBucket: 'pawtner-f96ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXxir--vomJIlrpkt5rVfacCubBU2hsk',
    appId: '1:736300186589:android:a995d337f796e39235d434',
    messagingSenderId: '736300186589',
    projectId: 'pawtner-f96ee',
    storageBucket: 'pawtner-f96ee.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCreiHrVIixELjukXsJZUMXOmJ5kNq0Beg',
    appId: '1:736300186589:ios:d06e1ef2b9b4441e35d434',
    messagingSenderId: '736300186589',
    projectId: 'pawtner-f96ee',
    storageBucket: 'pawtner-f96ee.firebasestorage.app',
    iosClientId: '736300186589-sa2v1jebl4nt6efm97f0uppuaeeu4ns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawtnerApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreiHrVIixELjukXsJZUMXOmJ5kNq0Beg',
    appId: '1:736300186589:ios:d06e1ef2b9b4441e35d434',
    messagingSenderId: '736300186589',
    projectId: 'pawtner-f96ee',
    storageBucket: 'pawtner-f96ee.firebasestorage.app',
    iosClientId: '736300186589-sa2v1jebl4nt6efm97f0uppuaeeu4ns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawtnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALIykaUQkxwiS_W4Ka_mnDecvsXrhkWYg',
    appId: '1:736300186589:web:5e5a5273e321294035d434',
    messagingSenderId: '736300186589',
    projectId: 'pawtner-f96ee',
    authDomain: 'pawtner-f96ee.firebaseapp.com',
    storageBucket: 'pawtner-f96ee.firebasestorage.app',
  );

}